// 语言资源文件
const langs = {
  en: {
    lang: 1,
    home: ' Home',
    service: 'Service',
    info: 'Info',
    me: 'Me',
    products: 'Products',
    merchants: 'Merchants',
    share: 'Share',
    bidding: 'Bidding',
    bid_status: 'Bid Status',
    quote: 'Quote',
    notstarted: 'Not started',
    ended: 'Closed',
    watching: 'Watching',
    certified_shop: 'Certified Shop',
    procurement: 'Procurement',
    bid: 'Bid',
    sell: 'Sell',
    selling: 'Selling',
    buy: 'Buy',
    buying: 'Buying',
    recommended: 'Recommended',
    new: 'New',
    see_all: 'See All',
    see_more: 'See More',
    current: 'Current',
    search: 'Search',
    news: 'INFO',
    keywords: 'Input keywords',
    country: 'Country',
    all: 'All',
    main_products: 'Main Products',
    select_main_products: 'Select Main Products',
    enter_shop_name: 'Enter Shop Name',
    view_shop: 'Shop',
    transactions: 'Transactions',
    transaction: 'Transaction',
    trader: 'Trader',
    factory: 'Factory',
    service_provider: 'Service Provider',
    sure: 'Confirm',
    cancel: 'Cancel',
    live: 'Live',
    fresh: 'Fresh',
    frozen: 'Frozen',
    dry_salt: 'Dry(salt)',
    products_center: 'Products Center',
    synthesize: 'All',
    price: 'Price',
    hot: 'Hot',
    filters: 'Filters',
    bidding1: 'Bidding',
    bidding2: 'Bidding',
    bid_failed: 'Bid Failed',
    bid_successful: 'Bid successful',
    merchant_quotation: "Merchant's quotation",
    number_of_bids: 'Number of bids',
    current_bid: 'Current bid',
    my_bid: 'My bid',
    check_my_bid_info: 'Check my bid information',
    my_quotation: 'My Quotation',
    my_biding: 'My Biding',
    order_details: 'Order Details',
    delete_order: 'Delete Order',
    order_number: 'Order Number',
    bidding_time: 'Bidding time',
    contact: 'Contact',
    bidding3: 'quoting',
    bidding_closed: 'Bidding Closed',
    start_in: 'start in',
    closes_in: 'Closes in',
    ends: 'Ends',
    weight: 'Weight',
    location: 'Location',
    production_date: 'Production Date',
    biding_detail: 'Biding Detail',
    rating: 'Rating',
    reviews: 'Reviews',
    follow: 'Follow',
    following: 'Following',
    credit: 'Credit',
    import_and_export: 'Import And Export',
    unfollow: 'Unfollow',
    merchant_info: 'Merchant Info',
    specifications: 'Specifications',
    comment: 'Comment',
    type: 'Type',
    commodity_type: 'Commodity type',
    classification: 'Classification',
    details_info: 'Details Info',
    grade: 'Grade',
    size: 'Size',
    quantity: 'Quantity',
    package: 'Package',
    net_weight: 'Net Weight',
    total_net_weight: 'Total net weight',
    unit_price: 'Unit Price',
    please_make_bid: 'make a bid',
    amount: 'Amount',
    total: 'Total',
    save: 'Save',
    saved: 'Saved',
    shop: 'Shop',
    to_bid: 'To bid',
    confirm_bid: 'Confirm Bid',
    support: 'Support',
    sercice: 'Sercice',
    followed_shops: 'Followed',
    saved_items: 'Saved',
    my_offer: 'My Offer',
    bid_records: 'Bid Records',
    revise_bid: 'Revise Bid',
    view_details: 'View Details',
    close_quote: 'Cancel',
    support_service: 'Service',
    region_filter: 'Region',
    customs_clearance: 'Clearance',
    po_financing: 'Financing',
    procurement_agent: 'Sourcing',
    cold_chain_logistics: 'Logistics',
    select_posting_type: 'Posting Type',
    please_select: 'Please Select',
    please_select_the_product_type: 'product type',
    post_product: 'Post Product',
    list_with_price_negotiation: 'List with Price Negotiation',
    post_buying_request: 'Post Buying Request',
    get_fast_quotes: 'Get Fast Quotes',
    publish_news: 'Publish News',
    real_time_market_insights: 'Real-time Market Insights',
    share_moments: 'Share Moments',
    fresh_content_alerts: 'Fresh Content Alerts',
    basic_information: 'Basic Information',
    product_name: 'Product Name',
    please_enter_product_name: 'enter product name',
    product_images: 'Product Images',
    product_details: 'Product Details',
    product_type: 'Product Type',
    country_of_origin: 'Country of Origin',
    Manufacturer: 'Factory (or Brand)',
    please_enter_Manufacturer: 'enter Factory',
    destination_port: 'Destination Port (Location)',
    please_enter_destination_port: 'enter destination port',
    production_date: 'Production Date',
    products_info: 'Please fill in the description of information related to the products, such as specific characteristics, Latin name, HS code, etc., which is conducive to a better understanding of your products by customers.',
    quotation: 'Quotation',
    quality_grade: 'Quality Grade',
    size_classification: 'Size Classification',
    weight_per_unit: 'Weight per Unit',
    quantity: 'Quantity',
    quantity1: 'Number of units',
    dollar: 'Dollar',
    yuan: 'Yuan',
    fill_in: 'Fill in',
    delete: 'Delete',
    add_quotation: 'Add Quotation',
    quotation_validity_period: 'Quotation Validity Period',
    start_date: 'Start Date',
    end_date: 'End Date',
    reset: 'Reset',
    submit: 'Submit',
    post_news: 'Post News',
    select_category: 'Select Category',
    cover_image: 'Cover Image',
    share_your_thoughts: 'Share Your Thoughts',
    share_post: 'Share a Post',
    say_mind: 'Say something on your mind',
    messages: 'Messages',
    input_title_keywords: 'Input Title Keywords',
    title: 'Title',
    feedback_title: 'Feedback title',
    business_community: 'Moments',
    supply_board: 'SD Board',
    market_intelligence: 'Market',
    regulatory_updates: 'Regulation',
    system_notification: 'System Notification',
    bid_updates: 'Bid Updates',
    merchant_support: 'Merchant Support',
    consult_immediately: 'Consult Immediately',
    new_follower: 'New Follower',
    reply: 'Reply',
    comment_reply: 'Comment Reply',
    merchant_reply: 'Merchant Reply',
    my_reply: 'My Reply',
    modify_reply: 'Modify Reply',
    dynamic_comment: 'Dynamic Comment',
    news_comment: 'News Comment',
    all_comment: 'All Comment',
    messages_from_system_notification: 'Messages from System Notification',
    new_bid_offer_received: 'New Bid Offer Received',
    new_merchant_inquiry: 'New Merchant Inquiry',
    new_follower_alert: 'New Follower Alert',
    response_to_customer_review: 'Response to Customer Review',
    lets_chat: 'Let’s Chat',
    personal: 'Personal',
    company: 'Company',
    company_address: 'Company Address',
    common_functions: 'Common functions',
    dashboard: 'Dashboard',
    quote_dashboard: 'Selling',
    bid_dashboard: 'Bidding',
    buy_dashboard: 'Buying',
    info_dashboard: 'INFO',
    merchant_settings: 'Shop Settings',
    merchant_verifi: 'Verification',
    shop_settings: 'Settings',
    service_certif: 'Certiication',
    business_card: 'Shop Card',
    cardcase: 'Card Holder',
    see_card: 'See_Card',
    myfollowing: 'Following',
    mysaved_items: 'Saved',
    saved_news: 'Saved News',
    followers: 'Followers',
    comment_dashboard: 'Comment',
    not_reply: 'Not Reply',
    all_comment: 'All Comment',
    live_chat: 'Live Chat',
    share_friends: 'Share Friends',
    about_us: 'About Us',
    feedback: 'Feedback',
    complaint: 'Complaint',
    no_see: 'No See',
    account_settings: 'Account',
    select_verification_type: 'Select Verification Type',
    business_license_verification: 'Business License Verification',
    id_card_verification: 'ID Card Verification',
    start_verification: 'Start Verification Now',
    immediate_certification: 'Immediate certification',
    verification_status: 'Verification Status',
    company_name: 'Company Name',
    business_registration_number: 'Business Registration Number',
    select_country: 'Select Country',
    region: 'Region',
    please_enter_your_city: 'enter your city',
    customs_registration_umber: 'Customs Registration Number',
    upload: 'Upload',
    upload_business_license: 'Upload Business License',
    authorized_representative: 'Authorized Representative',
    mobile_number: 'Mobile Number',
    email: 'Email',
    please_check_the_service: 'check the service agreement and Privacy agreement first',
    for_verification_purposes: 'For verification purposes only. Your data is securely encrypted',
    enter_representative_name: 'Enter Representative Name',
    enter: 'Enter',
    send: 'Send',
    enter_here: 'Enter here',
    your: 'your',
    product_bid_list: 'Product Bid List',
    business_license_verification1: 'Business License Verification',
    id_erification: 'ID Card Verification',
    name: 'Name',
    select_id_type: 'Select ID Type',
    id_card: 'ID Card',
    individual_business: 'Individual Business',
    passport: 'Passport',
    upload_your_id_card: 'Upload your ID Card',
    shop_logo: 'Shop LOGO',
    shop_name: 'Shop Name',
    shop_status: 'Shop Status',
    status: 'Status',
    opening_date: 'Opening Date',
    opening: 'Opening',
    not_open: 'Not Open',
    business_type: 'Business Type',
    value_added_services: 'Value-added Services',
    phone: 'Phone',
    operating_address: 'Operating Address',
    shop_description: 'Shop Description',
    save1: 'Save',
    profile_photo: 'Profile Photo',
    job: 'job',
    add_contact: 'Add Contact',
    merchant_contact: 'Merchant Contact',
    wechat: 'Wechat',
    verification_status: 'Verification Status',
    verification_failed: 'Verification Failed',
    to_be_certified: 'To Be Certified',
    verification: 'Verification',
    service_certification_application: 'Service Certification Application',
    certification_documents: 'Certification Documents',
    upload_required_certifications: 'Upload Required Certifications',
    additional_notes: 'Additional Notes',
    approved: 'Approved',
    openXbid: 'openXbid',
    phone_number_login: 'Phone number login',
    privacy_policy: 'I have read and agree to the Terms of Service and Privacy Policy',
    other_login_methods: 'Other login methods',
    account_login: 'Account login',
    verification_login: 'Verification login',
    password: 'Password',
    login: 'Login',
    verification_code: 'Verification code',
    back_to_social_login: 'Back to social login',
    back: 'Back',
    get_code: 'Get code',
    fish: 'Fish',
    crustacean: 'Crustacean',
    cephalopod: 'cephalopod',
    others: 'Others',
    others1: 'Others',
    requests: 'Requests',
    product_quotation_sheet: 'Product quotation sheet',
    product_editor: 'Product Editor',
    editor: 'Editor',
    buying_editor: 'Buying Editor',
    accept_proxy_procurement: 'Accept Proxy Procurement',
    no_complete: "You haven't completed your personal information yet. Please complete it first!",
    to_improve: 'To Improve',
    reminder: 'Reminder',
    merchant_news: 'Merchant News',
    client_consultation: 'Client Consultation',
    modify_phone_number: 'Modify Phone Number',
    modify_email: 'Modify Email',
    click_login: 'Click Login',
    rerelease: 'Rerelease',
    major_trading_countries: 'Major Trading Countries',
    function_registered: 'This function is only available to registered members',
    exit: 'Exit',
    sure_delete: 'Are you sure you want to delete it?',
  },
  'zh_CN': {
    lang: 2,
    home: '首页',
    service: '服务',
    info: '信息',
    me: '我的',
    products: '商品',
    merchants: '商家',
    share: '动态',
    bidding: '报价中',
    bid_status: '报价状态',
    quote: '报价',
    bidding3: '正在报价',
    notstarted: '未开始',
    ended: '已结束',
    watching: '围观',
    certified_shop: '认证商铺',
    procurement: '代采权',
    bid: '参与',
    sell: '出售',
    selling: '出售',
    buy: '求购',
    buying: '求购',
    recommended: '推荐',
    new: '最新',
    see_all: '查看全部',
    see_more: '查看更多',
    current: '当前价格',
    search: '搜索',
    news: '资讯',
    keywords: '输入关键词',
    country: '国家',
    all: '全部',
    main_products: '主营产品',
    select_main_products: '选择主营产品',
    enter_shop_name: '输入商铺名',
    view_shop: '进入商铺',
    transactions: '成交数',
    transaction: '成交',
    trader: '贸易商',
    factory: '厂家',
    service_provider: '服务商',
    sure: '确定',
    cancel: '取消',
    live: '活',
    fresh: '冰鲜',
    frozen: '冻品',
    dry_salt: '干(盐)品',
    products_center: '商品中心',
    synthesize: '综合',
    price: '价格',
    hot: '热度',
    filters: '筛选',
    bidding3: '正在报价',
    bidding2: '正在议价',
    bid_failed: '议价失败',
    bid_successful: '议价成功',
    merchant_quotation: '商家报价',
    number_of_bids: '出价次数',
    current_bid: '当前出价',
    my_bid: '我的出价',
    check_my_bid_info: '查看我的议价信息',
    my_quotation: '我的报价',
    my_biding: '我的仪价',
    order_details: '订单详情',
    delete_order: '删除订单',
    order_number: '订单号',
    bidding_time: '出价时间',
    contact: '联系客服',
    bidding1: '议价进行中',
    bidding_closed: '议价已结束',
    start_in: '距开始',
    closes_in: '距结束',
    ends: '结束时间',
    weight: '重量',
    location: '地点',
    production_date: '生产日期',
    biding_detail: '议价详情',
    rating: '评分',
    reviews: '评价',
    follow: '关注',
    following: '已关注',
    credit: '信誉',
    import_and_export: '进出口权',
    unfollow: '取消关注',
    merchant_info: '商家介绍',
    specifications: '商品详情',
    comment: '商品评论',
    commodity_type: '商品类型',
    type: '商品种类',
    classification: '商品分类',
    details_info: '商品补充信息',
    grade: '规格',
    size: '型号',
    quantity: '数量',
    package: '包装',
    net_weight: '净重',
    total_net_weight: '总净重',
    unit_price: '单价',
    please_make_bid: '请出价',
    amount: '总价',
    total: '总计',
    save: '收藏',
    saved: '已收藏',
    shop: '店铺',
    to_bid: '我来议价',
    confirm_bid: '确定出价',
    support: '辅助',
    sercice: '服务',
    followed_shops: '关注商家',
    saved_items: '收藏商品',
    saved_news: '收藏资讯',
    my_offer: '我的出价',
    bid_records: '报价列表',
    revise_bid: '修改出价',
    view_details: '查看详情',
    close_quote: '结束报价',
    support_service: '服务商家',
    region_filter: '地区筛选',
    customs_clearance: '清关服务',
    po_financing: '融资服务',
    procurement_agent: '代采服务',
    cold_chain_logistics: '冷库及物流',
    please_select: '请选择',
    please_select_the_product_type: '请先选择商品种类',
    select_posting_type: '请选择您要发布的内容',
    post_product: '发布产品',
    list_with_price_negotiation: '上架商品，竞价获客',
    post_buying_request: '发布求购',
    get_fast_quotes: '需求发布，快速响应',
    publish_news: '发布资讯',
    real_time_market_insights: '市场动态，实时掌握',
    share_moments: '发布动态',
    fresh_content_alerts: '新鲜内容，及时更新',
    basic_information: '基础信息',
    product_name: '商品名称',
    please_enter_product_name: '请填写商品名称',
    product_images: '商品图片',
    product_details: '商品信息',
    product_type: '商品性质',
    country_of_origin: '原产地',
    Manufacturer: '生产厂家（或品牌）',
    please_enter_Manufacturer: '请填写生产厂家',
    destination_port: '目的港（所在地）',
    please_enter_destination_port: '请填写目的港',
    production_date: '生产时间',
    products_info: '请填写与商品有关的信息描述，如具体特性、拉丁名、HS代码等，有利于客户更好了解您的商品.',
    quotation: '报价单',
    quality_grade: '质量等级',
    size_classification: '大小分类',
    weight_per_unit: '每件重量',
    quantity1: '件数',
    dollar: '美元',
    yuan: '人民币',
    fill_in: '请填写',
    delete: '删除',
    add_quotation: '添加报价单',
    quotation_validity_period: '报价有效期',
    start_date: '开始时间',
    end_date: '结束时间',
    reset: '重置',
    submit: '提交',
    post_news: '发布资讯',
    select_category: '选择要发布的栏目',
    cover_image: '资讯封面图',
    share_your_thoughts: '发表你的观点和看法',
    share_post: '发布了动态',
    say_mind: '说说你这一刻的想法',
    messages: '消息',
    input_title_keywords: '输入标题词',
    title: '标题',
    feedback_title: '反馈标题',
    business_community: '商家社区',
    supply_board: '供需看板',
    market_intelligence: '市场资讯',
    regulatory_updates: '政府法规',
    system_notification: '系统消息',
    bid_updates: '议价消息',
    merchant_support: '商家咨询',
    consult_immediately: '立即咨询',
    new_follower: '关注提醒',
    reply: '回复',
    comment_reply: '评价回复',
    merchant_reply: '商家回复',
    my_reply: '我的回复',
    modify_reply: '修改回复',
    dynamic_comment: '动态评论',
    news_comment: '资讯评论',
    all_comment: '全部评论',
    messages_from_system_notification: '系统消息通知',
    new_bid_offer_received: '议价消息通知',
    new_merchant_inquiry: '商家咨询通知',
    new_follower_alert: '客户关注消息通知',
    response_to_customer_review: '客户成功评价回复',
    lets_chat: '交流',
    personal: '个人认证',
    company: '企业认证',
    company_address: '企业地址',
    common_functions: '常用功能',
    dashboard: '管理',
    quote_dashboard: '报价管理',
    bid_dashboard: '议价管理',
    buy_dashboard: '求购管理',
    info_dashboard: '发布管理',
    merchant_settings: '商家设置',
    merchant_verifi: '商家认证',
    shop_settings: '商铺设置',
    service_certif: '服务资质',
    business_card: '商家名片',
    cardcase: '名片夹',
    see_card: '查看名片',
    myfollowing: '我的关注',
    mysaved_items: '我的收藏',
    followers: '我的粉丝',
    comment_dashboard: '评价管理',
    not_reply: '未回复',
    all_comment: '全部评价',
    live_chat: '在线留言',
    share_friends: '分享给好友',
    about_us: '关于平台',
    feedback: '意见反馈',
    complaint: '投诉举报',
    no_see: '不看他消息',
    account_settings: '系统设置',
    select_verification_type: '请选择您要认证的类型',
    business_license_verification: '企业营业执照认证',
    id_card_verification: '个人身份证认证',
    start_verification: '立即前往认证',
    immediate_certification: '立即认证',
    verification_status: '认证状态',
    verification_failed: '认证失败',
    to_be_certified: '待认证',
    verification: '认证中',
    company_name: '企业名称',
    business_registration_number: '社会信用代码',
    select_country: '请选择国家',
    region: '地区',
    please_enter_your_city: '请输入您所在城市',
    customs_registration_umber: '海关备案号',
    upload: '请上传',
    upload_business_license: '请上传营业执照',
    authorized_representative: '负责人',
    mobile_number: '手机号码',
    email: '邮箱',
    please_check_the_service: '请先勾选服务协议和隐私协议',
    for_verification_purposes: '仅用于评估认证，您的信息将严格保密',
    enter_representative_name: '请输入负责人',
    enter: '请输入',
    send: '发送',
    enter_here: '在此输入',
    your: '您的',
    product_bid_list: '商品议价单',
    business_license_verification1: '企业认证',
    id_erification: '个人认证',
    name: '姓名',
    select_id_type: '请选择证件类型',
    id_card: '身份证',
    individual_business: '个体工商户',
    passport: '护照',
    upload_your_id_card: '请上传身份证证件',
    shop_logo: '商铺LOGO',
    shop_name: '商铺名称',
    shop_status: '商铺状态',
    status: '状态',
    opening_date: '开通时间',
    opening: '已开通',
    not_open: '未开通',
    business_type: '商家性质',
    value_added_services: '增值服务',
    phone: '电话号码',
    operating_address: '经营地址',
    shop_description: '商铺介绍',
    save1: '保存',
    profile_photo: '头像',
    job: '职位',
    add_contact: '添加联系方式',
    merchant_contact: '商家联系人',
    wechat: '微信',
    verification_status: '认证状态',
    service_certification_application: '服务资质申请',
    certification_documents: '资质证明',
    upload_required_certifications: '请上传相关资质证明',
    additional_notes: '补充说明',
    approved: '认证成功',
    openXbid: '开拍鱼',
    phone_number_login: '手机号码一键登录',
    privacy_policy: '我已阅读、理解并同意《服务协议》及《隐私协议》',
    other_login_methods: '其他登录方式',
    account_login: '账号登录',
    verification_login: '验证码登录',
    password: '密码',
    login: '登录',
    verification_code: '验证码',
    back_to_social_login: '返回授权登录',
    back: '返回',
    get_code: '获取验证码',
    fish: '鱼类',
    crustacean: '甲壳类',
    cephalopod: '软体类',
    others: '其他类',
    others1: '其他',
    requests: '求购信息',
    product_quotation_sheet: '商品报价单',
    editor: '编辑',
    product_editor: '商品编辑',
    buying_editor: '求购编辑',
    accept_proxy_procurement: '接受代采',
    no_complete: "您还未完善个人资料，清先完善！",
    to_improve: '去完善',
    reminder: '提示',
    merchant_news: '商家消息',
    client_consultation: '客户咨询',
    modify_phone_number: '手机号码修改',
    modify_email: '邮箱修改',
    click_login: '点击登录',
    rerelease: '再次发布',
    major_trading_countries: '主要贸易国家',
    function_registered: '此项功能只针对注册会员',
    exit: '退出',
    sure_delete: '确定要删除吗？',
  }
}
// 判断是否为中文变体
function isChinese(lang) {
  return lang.startsWith('zh')
}

// 获取系统语言并返回对应的语言包
function getLanguage() {
  try {
    const systemInfo = wx.getAppBaseInfo()
    let language = systemInfo.language || systemInfo.appLanguage || 'en'

    // 标准化语言代码 (zh-CN → zh_CN)
    language = language.replace('-', '_')

    // 如果不是中文，则使用英文
    if (!isChinese(language)) {
      return langs['en']
    }

    // 如果是中文，返回对应的语言包或默认简体中文
    return langs['zh_CN']
    //return langs['en']
  } catch (e) {
    console.error('获取语言失败:', e)
    return langs['en']
  }
}

module.exports = {
  getLanguage,
  langs
}